version: 2
jobs:
  build:
    docker:
      - image: fedora:27
    steps:
      - checkout
      - run:
          name: Install Flatpak
          command: dnf install -y flatpak flatpak-builder
      - run:
          name: Run the Makefile script
          command: make build-ncoda
