version: 2
jobs:
  build:
    docker:
      - image: crantila/fedora-flatpak
    steps:
      - checkout
      - run:
          name: Install more things.
          command: |
            dnf install -y nodejs npm
      - run:
          name: Run the Makefile script.
          command: make build-ncoda
