version: 2
jobs:
  build:
    docker:
      - image: crantila/fedora-flatpak
    steps:
      - checkout
      - run:
          name: Install more things.
          command: |
            dnf install -y nodejs npm
            flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
            flatpak install -y flathub io.atom.electron.BaseApp
      
      - restore_cache:
          key: v1-npm-{{ checksum "julius-git/package.json" }}
      - run:
          name: Prepare the Julius build.
          command: make prepare-julius-build
      - save_cache:
          paths:
            - "julius-git/node_modules"
          key: v1-npm-{{ checksum "julius-git/package.json" }}
          when: on_success
      
      - run:
          name: Run the Makefile script.
          command: make build-ncoda
