version: 2
jobs:
  build:
    docker:
      - image: crantila/fedora-flatpak:nodejs
    steps:
      - checkout
      - run:
          name: Install more things.
          command: |
            flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
            flatpak install -y flathub io.atom.electron.BaseApp
            flatpak install flathub org.freedesktop.Sdk 1.6

      - run:
          name: Make a new user.
          command: useradd circleci

      - run:
          name: Checkout Julius.
          command: make checkout-julius
      - restore_cache:
          key: v1-npm-{{ checksum "julius-git/package.json" }}
      - run:
          name: Prepare the Julius build.
          command: make prepare-julius-build
      - save_cache:
          paths:
            - "julius-git/node_modules"
          key: v1-npm-{{ checksum "julius-git/package.json" }}
          when: on_success

      - run:
          name: Run the Makefile script.
          command: |
            "chown circleci: -R *"
            "cd ncoda && sudo -u circleci make build"
