version: 2
jobs:
  build:
    docker:
      - image: crantila/fedora-flatpak
    steps:
      - checkout
      - run:
          name: Make a new user.
          command: |
            dnf install -y sudo
            useradd circleci
            sudo -s -u circleci
            whoami
